import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppProvider } from './lib/provider'
import { fetchData } from './lib/fetch'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const variants = await fetchData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider products={variants}>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
